version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-surveys
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: surveysdb
      MYSQL_USER: surveyuser
      MYSQL_PASSWORD: surveypass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - surveys-network

  backend:
    build: .
    container_name: surveys-backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/surveysdb
      SPRING_DATASOURCE_USERNAME: surveyuser
      SPRING_DATASOURCE_PASSWORD: surveypass
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - surveys-network

volumes:
  mysql_data:

networks:
  surveys-network:
